swagger: '2.0'

info:
  title: {{name}}
  version: '1.0'

basePath: /api
produces:
- application/json
consumes:
- application/json
{{#swagger1st-oauth2}}

security:
- oauth2: [uid]
{{/swagger1st-oauth2}}

paths:
  /hello/{who}:
    get:
      operationId: {{namespace}}.api/get-hello
      parameters:
      - name: who
        in: path
        type: string
      responses:
        default:
          description: Say hello
{{#swagger1st-oauth2}}

securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
{{/swagger1st-oauth2}}
