swagger: '2.0'

info:
  title: {{name}}
  version: '1.0'

basePath: /api
produces:
- application/json
consumes:
- application/json

paths:
  '/hello/{who}':
    get:
      operationId: {{namespace}}.api/get-hello
      parameters:
      - name: who
        in: path
        type: string
      responses:
        default:
          description: Say hello
